/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package library_app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kgills
 */
public class LibraryApp extends javax.swing.JFrame {
    
    private Connection connect = null;
    private Statement statement = null;

    /**
     * Creates new form LibraryApp
     */
    public LibraryApp() {
        initComponents();
        this.setTitle("Library App");
        
        try {
            System.out.println("Opening localhost/library database");
            // Import the database, assuming that it was already populated
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/library?"
                                + "user=root&password=asdflkj&"
                                + "useSSL=false");
            
            // Statements allow to issue SQL queries to the database
            statement = connect.createStatement();
            
        } catch (Exception ex) {
            Logger.getLogger(LibraryApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(connect == null) {
            System.out.println("Error openening localhost/library database");
            System.exit(1);
        } else {
            System.out.println("Database Open!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewUserFrame = new javax.swing.JFrame();
        NameText = new javax.swing.JLabel();
        SSNText = new javax.swing.JLabel();
        AddressText = new javax.swing.JLabel();
        PhoneText = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        SSNField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        CreateUserButton = new javax.swing.JButton();
        NewUserDialog = new javax.swing.JDialog();
        NewUserStatus = new javax.swing.JLabel();
        FineFrame = new javax.swing.JFrame();
        UpdateFinesButton = new javax.swing.JButton();
        FineUserIDText = new javax.swing.JLabel();
        FineUserIDField = new javax.swing.JTextField();
        FineBalanceButton = new javax.swing.JButton();
        FinePayButton = new javax.swing.JButton();
        FinePayText = new javax.swing.JLabel();
        FinePayField = new javax.swing.JTextField();
        FineBalanceText = new javax.swing.JLabel();
        FineBalanceField = new javax.swing.JTextField();
        CheckInFrame = new javax.swing.JFrame();
        CheckInUserIDText = new javax.swing.JLabel();
        CheckInUserIDField = new javax.swing.JTextField();
        CheckInISBNText = new javax.swing.JLabel();
        CheckInISBNField = new javax.swing.JTextField();
        CheckInButton = new javax.swing.JButton();
        CheckInDialog = new javax.swing.JDialog();
        CheckInDialogText = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        SearchField = new javax.swing.JTextField();
        SearchResults = new javax.swing.JScrollPane();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        PayFine = new javax.swing.JMenuItem();
        NewUser = new javax.swing.JMenuItem();
        CheckIn = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();

        NameText.setText("Name");

        SSNText.setText("SSN");

        AddressText.setText("Address");

        PhoneText.setText("Phone");

        CreateUserButton.setText("Create");
        CreateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewUserFrameLayout = new javax.swing.GroupLayout(NewUserFrame.getContentPane());
        NewUserFrame.getContentPane().setLayout(NewUserFrameLayout);
        NewUserFrameLayout.setHorizontalGroup(
            NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewUserFrameLayout.createSequentialGroup()
                        .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameText)
                            .addComponent(SSNText)
                            .addComponent(AddressText)
                            .addComponent(PhoneText))
                        .addGap(18, 18, 18)
                        .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField)
                            .addComponent(SSNField)
                            .addComponent(AddressField, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                            .addComponent(PhoneField)))
                    .addGroup(NewUserFrameLayout.createSequentialGroup()
                        .addComponent(CreateUserButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewUserFrameLayout.setVerticalGroup(
            NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSNText)
                    .addComponent(SSNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressText)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneText)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateUserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NewUserStatus.setText("Error Creating User");

        javax.swing.GroupLayout NewUserDialogLayout = new javax.swing.GroupLayout(NewUserDialog.getContentPane());
        NewUserDialog.getContentPane().setLayout(NewUserDialogLayout);
        NewUserDialogLayout.setHorizontalGroup(
            NewUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewUserStatus)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        NewUserDialogLayout.setVerticalGroup(
            NewUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NewUserStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        UpdateFinesButton.setText("Update Fines");

        FineUserIDText.setText("User ID");

        FineBalanceButton.setText("Balance");

        FinePayButton.setText("Pay");

        FinePayText.setText("Pay");

        FineBalanceText.setText("Balance");

        javax.swing.GroupLayout FineFrameLayout = new javax.swing.GroupLayout(FineFrame.getContentPane());
        FineFrame.getContentPane().setLayout(FineFrameLayout);
        FineFrameLayout.setHorizontalGroup(
            FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FineFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FineFrameLayout.createSequentialGroup()
                        .addComponent(FineBalanceButton)
                        .addGap(18, 18, 18)
                        .addComponent(FinePayButton)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateFinesButton))
                    .addGroup(FineFrameLayout.createSequentialGroup()
                        .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FineUserIDText)
                            .addComponent(FinePayText)
                            .addComponent(FineBalanceText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FineUserIDField)
                            .addComponent(FinePayField)
                            .addComponent(FineBalanceField))))
                .addContainerGap())
        );
        FineFrameLayout.setVerticalGroup(
            FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FineFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FineUserIDText)
                    .addComponent(FineUserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinePayText)
                    .addComponent(FinePayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FineBalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FineBalanceText))
                .addGap(26, 26, 26)
                .addGroup(FineFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FineBalanceButton)
                    .addComponent(FinePayButton)
                    .addComponent(UpdateFinesButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckInUserIDText.setText("UserID:");

        CheckInISBNText.setText("ISBN: ");

        CheckInButton.setText("Check In");
        CheckInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CheckInFrameLayout = new javax.swing.GroupLayout(CheckInFrame.getContentPane());
        CheckInFrame.getContentPane().setLayout(CheckInFrameLayout);
        CheckInFrameLayout.setHorizontalGroup(
            CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckInFrameLayout.createSequentialGroup()
                        .addComponent(CheckInButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CheckInFrameLayout.createSequentialGroup()
                        .addGroup(CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckInUserIDText)
                            .addComponent(CheckInISBNText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckInISBNField, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(CheckInUserIDField))))
                .addContainerGap())
        );
        CheckInFrameLayout.setVerticalGroup(
            CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInUserIDText)
                    .addComponent(CheckInUserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CheckInFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckInISBNText)
                    .addComponent(CheckInISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CheckInButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckInDialogText.setText("Error Checking In");

        javax.swing.GroupLayout CheckInDialogLayout = new javax.swing.GroupLayout(CheckInDialog.getContentPane());
        CheckInDialog.getContentPane().setLayout(CheckInDialogLayout);
        CheckInDialogLayout.setHorizontalGroup(
            CheckInDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckInDialogText)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        CheckInDialogLayout.setVerticalGroup(
            CheckInDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckInDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CheckInDialogText)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        PayFine.setText("Pay Fine");
        PayFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayFineActionPerformed(evt);
            }
        });
        FileMenu.add(PayFine);

        NewUser.setText("New User");
        NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUserActionPerformed(evt);
            }
        });
        FileMenu.add(NewUser);

        CheckIn.setText("Check In");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        FileMenu.add(CheckIn);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        FileMenu.add(Exit);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchResults)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchField, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchButton)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayFineActionPerformed
        // TODO add your handling code here:
        FineFrame.pack();
        FineFrame.setTitle("Fines");
        FineFrame.setVisible(true);
    }//GEN-LAST:event_PayFineActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // Close the DB connection
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUserActionPerformed

        NewUserFrame.pack();
        NewUserFrame.setTitle("New User");
        NewUserFrame.setVisible(true);
    }//GEN-LAST:event_NewUserActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        CheckInFrame.pack();
        CheckInFrame.setTitle("Check In");
        CheckInFrame.setVisible(true);
    }//GEN-LAST:event_CheckInActionPerformed

    private void CreateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUserButtonActionPerformed

        NewUserDialog.pack();
        NewUserDialog.setTitle("New User Status");
        NewUserDialog.setVisible(true);
    }//GEN-LAST:event_CreateUserButtonActionPerformed

    private void CheckInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInButtonActionPerformed
        CheckInDialog.pack();
        CheckInDialog.setTitle("Check In Status");
        CheckInDialog.setVisible(true);
    }//GEN-LAST:event_CheckInButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        
        ResultSet authorResultSet = null;
        
        try {
            // Query the database for whatever is in the search bar
            String query = "SELECT Author_id "
                     + "FROM AUTHORS "
                     + "WHERE LOWER(AUTHORS.name) LIKE '%"+SearchField.getText()+"%';";
            System.out.println(query);
             
             authorResultSet = statement.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(LibraryApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(authorResultSet == null) {
            System.out.println("No results");
        } else {
            try {
                ResultSetMetaData rsmd = authorResultSet.getMetaData();
                int columnsNumber = rsmd.getColumnCount();
                while (authorResultSet.next()) {
                    for (int i = 1; i <= columnsNumber; i++) {
                        if (i > 1) System.out.print(",  ");
                        String columnValue = authorResultSet.getString(i);
                        System.out.print(columnValue + " " + rsmd.getColumnName(i));
                    }
                    System.out.println("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LibraryApp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        System.out.println("Staring Library Database Application");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LibraryApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel AddressText;
    private javax.swing.JMenuItem CheckIn;
    private javax.swing.JButton CheckInButton;
    private javax.swing.JDialog CheckInDialog;
    private javax.swing.JLabel CheckInDialogText;
    private javax.swing.JFrame CheckInFrame;
    private javax.swing.JTextField CheckInISBNField;
    private javax.swing.JLabel CheckInISBNText;
    private javax.swing.JTextField CheckInUserIDField;
    private javax.swing.JLabel CheckInUserIDText;
    private javax.swing.JButton CreateUserButton;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JButton FineBalanceButton;
    private javax.swing.JTextField FineBalanceField;
    private javax.swing.JLabel FineBalanceText;
    private javax.swing.JFrame FineFrame;
    private javax.swing.JButton FinePayButton;
    private javax.swing.JTextField FinePayField;
    private javax.swing.JLabel FinePayText;
    private javax.swing.JTextField FineUserIDField;
    private javax.swing.JLabel FineUserIDText;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameText;
    private javax.swing.JMenuItem NewUser;
    private javax.swing.JDialog NewUserDialog;
    private javax.swing.JFrame NewUserFrame;
    private javax.swing.JLabel NewUserStatus;
    private javax.swing.JMenuItem PayFine;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JLabel PhoneText;
    private javax.swing.JTextField SSNField;
    private javax.swing.JLabel SSNText;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JScrollPane SearchResults;
    private javax.swing.JButton UpdateFinesButton;
    // End of variables declaration//GEN-END:variables
}
